//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbsCompleteTest.GinaBase7
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseException", Namespace="http://exceptions.soap.base.client.chipkarte.at")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AbsCompleteTest.GinaBase7.CardException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AbsCompleteTest.GinaBase7.ServiceException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AbsCompleteTest.GinaBase7.BCardException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AbsCompleteTest.GinaBase7.AccessException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AbsCompleteTest.GinaBase7.DialogException))]
    public partial class BaseException : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string codeField;
        
        private int errorCodeField;
        
        private string messageField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardException", Namespace="http://exceptions.soap.base.client.chipkarte.at")]
    public partial class CardException : AbsCompleteTest.GinaBase7.BaseException
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceException", Namespace="http://exceptions.soap.base.client.chipkarte.at")]
    public partial class ServiceException : AbsCompleteTest.GinaBase7.BaseException
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BCardException", Namespace="http://exceptions.soap.base.client.chipkarte.at")]
    public partial class BCardException : AbsCompleteTest.GinaBase7.BaseException
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccessException", Namespace="http://exceptions.soap.base.client.chipkarte.at")]
    public partial class AccessException : AbsCompleteTest.GinaBase7.BaseException
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DialogException", Namespace="http://exceptions.soap.base.client.chipkarte.at")]
    public partial class DialogException : AbsCompleteTest.GinaBase7.BaseException
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://vp.soap.base.client.chipkarte.at", ConfigurationName="AbsCompleteTest.GinaBase7.IBaseServiceVP")]
    public interface IBaseServiceVP
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaBase7.DialogException), Action="", Name="fault1")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaBase7.ServiceException), Action="", Name="fault2")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaBase7.CardException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="createDialogReturn")]
        string createDialog(string cardReaderId, AbsCompleteTest.GinaBase7.ProduktInfo produktInfo, string extUID);
        
        // CODEGEN: Parameter 'getCardReadersReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaBase7.ServiceException), Action="", Name="fault2")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getCardReadersReturn")]
        AbsCompleteTest.GinaBase7.getCardReadersResponse getCardReaders(AbsCompleteTest.GinaBase7.getCardReadersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaBase7.ServiceException), Action="", Name="fault2")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaBase7.CardException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getCardDataReturn")]
        AbsCompleteTest.GinaBase7.Card getCardData(string cardReaderId);
        
        // CODEGEN: Parameter 'getExtendedCardDataReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaBase7.ServiceException), Action="", Name="fault2")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaBase7.CardException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getExtendedCardDataReturn")]
        AbsCompleteTest.GinaBase7.getExtendedCardDataResponse getExtendedCardData(AbsCompleteTest.GinaBase7.getExtendedCardDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaBase7.ServiceException), Action="", Name="fault2")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaBase7.CardException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void changePin(string cardReaderId, string cin, string oldPin, string newPin);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaBase7.ServiceException), Action="", Name="fault2")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaBase7.CardException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void changePinWithPuk(string cardReaderId, string cin, string puk, string newPin);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaBase7.ServiceException), Action="", Name="fault2")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaBase7.CardException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="doCardTestReturn")]
        int doCardTest(string cardReaderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaBase7.DialogException), Action="", Name="fault1")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaBase7.ServiceException), Action="", Name="fault2")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaBase7.CardException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="authenticateDialogReturn")]
        AbsCompleteTest.GinaBase7.Vertragspartner authenticateDialog(string dialogId, string cin, string pin, int systemType, string cardReaderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaBase7.DialogException), Action="", Name="fault1")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaBase7.ServiceException), Action="", Name="fault2")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void setDialogAddress(string dialogId, string ordinationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaBase7.DialogException), Action="", Name="fault1")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaBase7.ServiceException), Action="", Name="fault2")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void closeDialog(string dialogId);
        
        // CODEGEN: Parameter 'checkStatusReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaBase7.DialogException), Action="", Name="fault1")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaBase7.ServiceException), Action="", Name="fault2")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="checkStatusReturn")]
        AbsCompleteTest.GinaBase7.checkStatusResponse checkStatus(AbsCompleteTest.GinaBase7.checkStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaBase7.DialogException), Action="", Name="fault1")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaBase7.ServiceException), Action="", Name="fault2")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void uebersiedelnOrdination(string dialogId, string ordinationId);
        
        // CODEGEN: Parameter 'getMessagesReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaBase7.DialogException), Action="", Name="fault1")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaBase7.ServiceException), Action="", Name="fault2")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getMessagesReturn")]
        AbsCompleteTest.GinaBase7.getMessagesResponse getMessages(AbsCompleteTest.GinaBase7.getMessagesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getFreeDialogsReturn")]
        AbsCompleteTest.GinaBase7.DialogsInfo getFreeDialogs();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getGinaSoftwareVersionReturn")]
        string getGinaSoftwareVersion();
        
        // CODEGEN: Parameter 'getVertraegeReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaBase7.DialogException), Action="", Name="fault1")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaBase7.ServiceException), Action="", Name="fault2")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getVertraegeReturn")]
        AbsCompleteTest.GinaBase7.getVertraegeResponse getVertraege(AbsCompleteTest.GinaBase7.getVertraegeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaBase7.BCardException), Action="", Name="fault3")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaBase7.DialogException), Action="", Name="fault1")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaBase7.ServiceException), Action="", Name="fault2")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaBase7.CardException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getBCardSvPersonReturn")]
        AbsCompleteTest.GinaBase7.SvPerson getBCardSvPerson(string dialogId, bool forceExecution, string readerId);
        
        // CODEGEN: Parameter 'getSVTsReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaBase7.ServiceException), Action="", Name="fault2")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getSVTsReturn")]
        AbsCompleteTest.GinaBase7.getSVTsResponse getSVTs(AbsCompleteTest.GinaBase7.getSVTsRequest request);
        
        // CODEGEN: Parameter 'getFachgebieteReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaBase7.ServiceException), Action="", Name="fault2")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getFachgebieteReturn")]
        AbsCompleteTest.GinaBase7.getFachgebieteResponse getFachgebiete(AbsCompleteTest.GinaBase7.getFachgebieteRequest request);
        
        // CODEGEN: Parameter 'getFachgebieteByOrdIdReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaBase7.DialogException), Action="", Name="fault1")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaBase7.ServiceException), Action="", Name="fault2")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getFachgebieteByOrdIdReturn")]
        AbsCompleteTest.GinaBase7.getFachgebieteByOrdIdResponse getFachgebieteByOrdId(AbsCompleteTest.GinaBase7.getFachgebieteByOrdIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getGinaAndServiceavailabilityInformationReturn")]
        AbsCompleteTest.GinaBase7.StatusInformationen getGinaAndServiceavailabilityInformation();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaBase7.DialogException), Action="", Name="fault1")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaBase7.ServiceException), Action="", Name="fault2")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaBase7.CardException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void setCardReader(string dialogId, string cardReaderId);
        
        // CODEGEN: Parameter 'cardReaderId' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaBase7.ServiceException), Action="", Name="fault2")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaBase7.CardException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getReaderStatusEventsReturn")]
        AbsCompleteTest.GinaBase7.getReaderStatusEventsResponse getReaderStatusEvents(AbsCompleteTest.GinaBase7.getReaderStatusEventsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaBase7.ServiceException), Action="", Name="fault2")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaBase7.CardException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void releaseCardReader(string cardReaderId);
        
        // CODEGEN: Parameter 'getBerechtigungenReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaBase7.DialogException), Action="", Name="fault1")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaBase7.ServiceException), Action="", Name="fault2")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getBerechtigungenReturn")]
        AbsCompleteTest.GinaBase7.getBerechtigungenResponse getBerechtigungen(AbsCompleteTest.GinaBase7.getBerechtigungenRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://vp.soap.base.client.chipkarte.at")]
    public partial class ProduktInfo
    {
        
        private int produktIdField;
        
        private string produktVersionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int produktId
        {
            get
            {
                return this.produktIdField;
            }
            set
            {
                this.produktIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string produktVersion
        {
            get
            {
                return this.produktVersionField;
            }
            set
            {
                this.produktVersionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.base.client.chipkarte.at")]
    public partial class ReaderStatusEvent
    {
        
        private string cardReaderIdField;
        
        private string cardReaderStateField;
        
        private string cardTypeField;
        
        private string eventTypeField;
        
        private string timeStampField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string cardReaderId
        {
            get
            {
                return this.cardReaderIdField;
            }
            set
            {
                this.cardReaderIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string cardReaderState
        {
            get
            {
                return this.cardReaderStateField;
            }
            set
            {
                this.cardReaderStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string cardType
        {
            get
            {
                return this.cardTypeField;
            }
            set
            {
                this.cardTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string eventType
        {
            get
            {
                return this.eventTypeField;
            }
            set
            {
                this.eventTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string timeStamp
        {
            get
            {
                return this.timeStampField;
            }
            set
            {
                this.timeStampField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.base.client.chipkarte.at")]
    public partial class ReaderStatusResult
    {
        
        private string handleField;
        
        private ReaderStatusEvent[] readerStatusEventsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string handle
        {
            get
            {
                return this.handleField;
            }
            set
            {
                this.handleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("readerStatusEvents", IsNullable=true, Order=1)]
        public ReaderStatusEvent[] readerStatusEvents
        {
            get
            {
                return this.readerStatusEventsField;
            }
            set
            {
                this.readerStatusEventsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.base.client.chipkarte.at")]
    public partial class ServiceStatusInformation
    {
        
        private string hinweisAktionField;
        
        private string hinweisZusatzField;
        
        private bool modusField;
        
        private string modusTextField;
        
        private string serviceNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string hinweisAktion
        {
            get
            {
                return this.hinweisAktionField;
            }
            set
            {
                this.hinweisAktionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string hinweisZusatz
        {
            get
            {
                return this.hinweisZusatzField;
            }
            set
            {
                this.hinweisZusatzField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool modus
        {
            get
            {
                return this.modusField;
            }
            set
            {
                this.modusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string modusText
        {
            get
            {
                return this.modusTextField;
            }
            set
            {
                this.modusTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string serviceName
        {
            get
            {
                return this.serviceNameField;
            }
            set
            {
                this.serviceNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.base.client.chipkarte.at")]
    public partial class GinaInfo
    {
        
        private string dnsNameField;
        
        private string ipAdresseField;
        
        private bool isdnKennzeichenField;
        
        private string produktVersionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string dnsName
        {
            get
            {
                return this.dnsNameField;
            }
            set
            {
                this.dnsNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string ipAdresse
        {
            get
            {
                return this.ipAdresseField;
            }
            set
            {
                this.ipAdresseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool isdnKennzeichen
        {
            get
            {
                return this.isdnKennzeichenField;
            }
            set
            {
                this.isdnKennzeichenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string produktVersion
        {
            get
            {
                return this.produktVersionField;
            }
            set
            {
                this.produktVersionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.base.client.chipkarte.at")]
    public partial class StatusInformationen
    {
        
        private GinaInfo ginaInfoField;
        
        private ServiceStatusInformation[] serviceStatusInformationField;
        
        private string wartungsfensterBisField;
        
        private string wartungsfensterHinweisField;
        
        private bool wartungsfensterKennzeichenField;
        
        private string wartungsfensterTextField;
        
        private string wartungsfensterVonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public GinaInfo ginaInfo
        {
            get
            {
                return this.ginaInfoField;
            }
            set
            {
                this.ginaInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("serviceStatusInformation", IsNullable=true, Order=1)]
        public ServiceStatusInformation[] serviceStatusInformation
        {
            get
            {
                return this.serviceStatusInformationField;
            }
            set
            {
                this.serviceStatusInformationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string wartungsfensterBis
        {
            get
            {
                return this.wartungsfensterBisField;
            }
            set
            {
                this.wartungsfensterBisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string wartungsfensterHinweis
        {
            get
            {
                return this.wartungsfensterHinweisField;
            }
            set
            {
                this.wartungsfensterHinweisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool wartungsfensterKennzeichen
        {
            get
            {
                return this.wartungsfensterKennzeichenField;
            }
            set
            {
                this.wartungsfensterKennzeichenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string wartungsfensterText
        {
            get
            {
                return this.wartungsfensterTextField;
            }
            set
            {
                this.wartungsfensterTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string wartungsfensterVon
        {
            get
            {
                return this.wartungsfensterVonField;
            }
            set
            {
                this.wartungsfensterVonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SvtProperty))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.base.client.chipkarte.at")]
    public partial class BaseProperty
    {
        
        private string codeField;
        
        private bool nurAnzeigeField;
        
        private string textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool nurAnzeige
        {
            get
            {
                return this.nurAnzeigeField;
            }
            set
            {
                this.nurAnzeigeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.base.client.chipkarte.at")]
    public partial class SvtProperty : BaseProperty
    {
        
        private bool aSVGField;
        
        private string eKVKCodeField;
        
        private string eKVKNameField;
        
        private string kurzbezeichnungField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool ASVG
        {
            get
            {
                return this.aSVGField;
            }
            set
            {
                this.aSVGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string EKVKCode
        {
            get
            {
                return this.eKVKCodeField;
            }
            set
            {
                this.eKVKCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string EKVKName
        {
            get
            {
                return this.eKVKNameField;
            }
            set
            {
                this.eKVKNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string kurzbezeichnung
        {
            get
            {
                return this.kurzbezeichnungField;
            }
            set
            {
                this.kurzbezeichnungField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.base.client.chipkarte.at")]
    public partial class SvPerson
    {
        
        private string geburtsdatumField;
        
        private string geschlechtField;
        
        private string nachnameField;
        
        private string svNummerField;
        
        private string titelHintenField;
        
        private string titelVorneField;
        
        private string vornameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string geburtsdatum
        {
            get
            {
                return this.geburtsdatumField;
            }
            set
            {
                this.geburtsdatumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string geschlecht
        {
            get
            {
                return this.geschlechtField;
            }
            set
            {
                this.geschlechtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string nachname
        {
            get
            {
                return this.nachnameField;
            }
            set
            {
                this.nachnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string svNummer
        {
            get
            {
                return this.svNummerField;
            }
            set
            {
                this.svNummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string titelHinten
        {
            get
            {
                return this.titelHintenField;
            }
            set
            {
                this.titelHintenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string titelVorne
        {
            get
            {
                return this.titelVorneField;
            }
            set
            {
                this.titelVorneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string vorname
        {
            get
            {
                return this.vornameField;
            }
            set
            {
                this.vornameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.base.client.chipkarte.at")]
    public partial class VertragsDaten
    {
        
        private string bezBereichField;
        
        private string fachGebietsCodeField;
        
        private bool konsultationsrechtField;
        
        private string leistungsSVTField;
        
        private string ordIdField;
        
        private bool rezepturrechtField;
        
        private string verrechnungsSVTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string bezBereich
        {
            get
            {
                return this.bezBereichField;
            }
            set
            {
                this.bezBereichField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string fachGebietsCode
        {
            get
            {
                return this.fachGebietsCodeField;
            }
            set
            {
                this.fachGebietsCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool konsultationsrecht
        {
            get
            {
                return this.konsultationsrechtField;
            }
            set
            {
                this.konsultationsrechtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string leistungsSVT
        {
            get
            {
                return this.leistungsSVTField;
            }
            set
            {
                this.leistungsSVTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string ordId
        {
            get
            {
                return this.ordIdField;
            }
            set
            {
                this.ordIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool rezepturrecht
        {
            get
            {
                return this.rezepturrechtField;
            }
            set
            {
                this.rezepturrechtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string verrechnungsSVT
        {
            get
            {
                return this.verrechnungsSVTField;
            }
            set
            {
                this.verrechnungsSVTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.base.client.chipkarte.at")]
    public partial class DialogsInfo
    {
        
        private int currentDialogsCountField;
        
        private int maxDialogsCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int currentDialogsCount
        {
            get
            {
                return this.currentDialogsCountField;
            }
            set
            {
                this.currentDialogsCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int maxDialogsCount
        {
            get
            {
                return this.maxDialogsCountField;
            }
            set
            {
                this.maxDialogsCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.base.client.chipkarte.at")]
    public partial class Message
    {
        
        private string appidField;
        
        private string categoryField;
        
        private string dataField;
        
        private string idField;
        
        private string textField;
        
        private string timestampField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string appid
        {
            get
            {
                return this.appidField;
            }
            set
            {
                this.appidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string timestamp
        {
            get
            {
                return this.timestampField;
            }
            set
            {
                this.timestampField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.base.client.chipkarte.at")]
    public partial class Ordination
    {
        
        private string bezirkField;
        
        private string bundeslandCodeField;
        
        private string landCodeField;
        
        private string ordinationIdField;
        
        private long ordinationNumberField;
        
        private string postleitzahlField;
        
        private string stadtField;
        
        private string strasseField;
        
        private bool uebersiedelnField;
        
        private string uebersiedelnDateField;
        
        private string vorgaengerOrdinationIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string bezirk
        {
            get
            {
                return this.bezirkField;
            }
            set
            {
                this.bezirkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string bundeslandCode
        {
            get
            {
                return this.bundeslandCodeField;
            }
            set
            {
                this.bundeslandCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string landCode
        {
            get
            {
                return this.landCodeField;
            }
            set
            {
                this.landCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string ordinationId
        {
            get
            {
                return this.ordinationIdField;
            }
            set
            {
                this.ordinationIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public long ordinationNumber
        {
            get
            {
                return this.ordinationNumberField;
            }
            set
            {
                this.ordinationNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string postleitzahl
        {
            get
            {
                return this.postleitzahlField;
            }
            set
            {
                this.postleitzahlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string stadt
        {
            get
            {
                return this.stadtField;
            }
            set
            {
                this.stadtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string strasse
        {
            get
            {
                return this.strasseField;
            }
            set
            {
                this.strasseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool uebersiedeln
        {
            get
            {
                return this.uebersiedelnField;
            }
            set
            {
                this.uebersiedelnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string uebersiedelnDate
        {
            get
            {
                return this.uebersiedelnDateField;
            }
            set
            {
                this.uebersiedelnDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string vorgaengerOrdinationId
        {
            get
            {
                return this.vorgaengerOrdinationIdField;
            }
            set
            {
                this.vorgaengerOrdinationIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.base.client.chipkarte.at")]
    public partial class AuthenticationStatus
    {
        
        private int failedLoginAttemptsField;
        
        private int failedPINAttemptsField;
        
        private string lastLoginDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int failedLoginAttempts
        {
            get
            {
                return this.failedLoginAttemptsField;
            }
            set
            {
                this.failedLoginAttemptsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int failedPINAttempts
        {
            get
            {
                return this.failedPINAttemptsField;
            }
            set
            {
                this.failedPINAttemptsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string lastLoginDate
        {
            get
            {
                return this.lastLoginDateField;
            }
            set
            {
                this.lastLoginDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.base.client.chipkarte.at")]
    public partial class Vertragspartner
    {
        
        private string anredeCodeField;
        
        private AuthenticationStatus authenticationStatusField;
        
        private string druckNachnameField;
        
        private string druckVornameField;
        
        private string geburtsdatumField;
        
        private string nachnameField;
        
        private string niederlassungsgrundCodeField;
        
        private Ordination[] ordinationField;
        
        private string titelHintenField;
        
        private string titelVorneField;
        
        private string vornameField;
        
        private string vpIdField;
        
        private string vpNummerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string anredeCode
        {
            get
            {
                return this.anredeCodeField;
            }
            set
            {
                this.anredeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public AuthenticationStatus authenticationStatus
        {
            get
            {
                return this.authenticationStatusField;
            }
            set
            {
                this.authenticationStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string druckNachname
        {
            get
            {
                return this.druckNachnameField;
            }
            set
            {
                this.druckNachnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string druckVorname
        {
            get
            {
                return this.druckVornameField;
            }
            set
            {
                this.druckVornameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string geburtsdatum
        {
            get
            {
                return this.geburtsdatumField;
            }
            set
            {
                this.geburtsdatumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string nachname
        {
            get
            {
                return this.nachnameField;
            }
            set
            {
                this.nachnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string niederlassungsgrundCode
        {
            get
            {
                return this.niederlassungsgrundCodeField;
            }
            set
            {
                this.niederlassungsgrundCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ordination", IsNullable=true, Order=7)]
        public Ordination[] ordination
        {
            get
            {
                return this.ordinationField;
            }
            set
            {
                this.ordinationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string titelHinten
        {
            get
            {
                return this.titelHintenField;
            }
            set
            {
                this.titelHintenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string titelVorne
        {
            get
            {
                return this.titelVorneField;
            }
            set
            {
                this.titelVorneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string vorname
        {
            get
            {
                return this.vornameField;
            }
            set
            {
                this.vornameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string vpId
        {
            get
            {
                return this.vpIdField;
            }
            set
            {
                this.vpIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public string vpNummer
        {
            get
            {
                return this.vpNummerField;
            }
            set
            {
                this.vpNummerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.base.client.chipkarte.at")]
    public partial class Property
    {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.base.client.chipkarte.at")]
    public partial class Card
    {
        
        private string cardTypeField;
        
        private string cinField;
        
        private string csnField;
        
        private string geburtsdatumField;
        
        private string geschlechtCodeField;
        
        private string nachnameField;
        
        private string nachnameLatin1Field;
        
        private string nummerField;
        
        private string titelField;
        
        private string titelHintenField;
        
        private string titelHintenLatin1Field;
        
        private string titelLatin1Field;
        
        private string vornameField;
        
        private string vornameLatin1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string cardType
        {
            get
            {
                return this.cardTypeField;
            }
            set
            {
                this.cardTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string cin
        {
            get
            {
                return this.cinField;
            }
            set
            {
                this.cinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string csn
        {
            get
            {
                return this.csnField;
            }
            set
            {
                this.csnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string geburtsdatum
        {
            get
            {
                return this.geburtsdatumField;
            }
            set
            {
                this.geburtsdatumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string geschlechtCode
        {
            get
            {
                return this.geschlechtCodeField;
            }
            set
            {
                this.geschlechtCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string nachname
        {
            get
            {
                return this.nachnameField;
            }
            set
            {
                this.nachnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string nachnameLatin1
        {
            get
            {
                return this.nachnameLatin1Field;
            }
            set
            {
                this.nachnameLatin1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string nummer
        {
            get
            {
                return this.nummerField;
            }
            set
            {
                this.nummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string titel
        {
            get
            {
                return this.titelField;
            }
            set
            {
                this.titelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string titelHinten
        {
            get
            {
                return this.titelHintenField;
            }
            set
            {
                this.titelHintenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string titelHintenLatin1
        {
            get
            {
                return this.titelHintenLatin1Field;
            }
            set
            {
                this.titelHintenLatin1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string titelLatin1
        {
            get
            {
                return this.titelLatin1Field;
            }
            set
            {
                this.titelLatin1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public string vorname
        {
            get
            {
                return this.vornameField;
            }
            set
            {
                this.vornameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public string vornameLatin1
        {
            get
            {
                return this.vornameLatin1Field;
            }
            set
            {
                this.vornameLatin1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.base.client.chipkarte.at")]
    public partial class CardReader
    {
        
        private string idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCardReaders", WrapperNamespace="http://vp.soap.base.client.chipkarte.at", IsWrapped=true)]
    public partial class getCardReadersRequest
    {
        
        public getCardReadersRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCardReadersResponse", WrapperNamespace="http://vp.soap.base.client.chipkarte.at", IsWrapped=true)]
    public partial class getCardReadersResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://vp.soap.base.client.chipkarte.at", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getCardReadersReturn", IsNullable=true)]
        public CardReader[] getCardReadersReturn;
        
        public getCardReadersResponse()
        {
        }
        
        public getCardReadersResponse(CardReader[] getCardReadersReturn)
        {
            this.getCardReadersReturn = getCardReadersReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getExtendedCardData", WrapperNamespace="http://vp.soap.base.client.chipkarte.at", IsWrapped=true)]
    public partial class getExtendedCardDataRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://vp.soap.base.client.chipkarte.at", Order=0)]
        public string cardReaderId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://vp.soap.base.client.chipkarte.at", Order=1)]
        public string CIN;
        
        public getExtendedCardDataRequest()
        {
        }
        
        public getExtendedCardDataRequest(string cardReaderId, string CIN)
        {
            this.cardReaderId = cardReaderId;
            this.CIN = CIN;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getExtendedCardDataResponse", WrapperNamespace="http://vp.soap.base.client.chipkarte.at", IsWrapped=true)]
    public partial class getExtendedCardDataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://vp.soap.base.client.chipkarte.at", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getExtendedCardDataReturn", IsNullable=true)]
        public Property[] getExtendedCardDataReturn;
        
        public getExtendedCardDataResponse()
        {
        }
        
        public getExtendedCardDataResponse(Property[] getExtendedCardDataReturn)
        {
            this.getExtendedCardDataReturn = getExtendedCardDataReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkStatus", WrapperNamespace="http://vp.soap.base.client.chipkarte.at", IsWrapped=true)]
    public partial class checkStatusRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://vp.soap.base.client.chipkarte.at", Order=0)]
        public string dialogId;
        
        public checkStatusRequest()
        {
        }
        
        public checkStatusRequest(string dialogId)
        {
            this.dialogId = dialogId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkStatusResponse", WrapperNamespace="http://vp.soap.base.client.chipkarte.at", IsWrapped=true)]
    public partial class checkStatusResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://vp.soap.base.client.chipkarte.at", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("checkStatusReturn")]
        public Property[] checkStatusReturn;
        
        public checkStatusResponse()
        {
        }
        
        public checkStatusResponse(Property[] checkStatusReturn)
        {
            this.checkStatusReturn = checkStatusReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMessages", WrapperNamespace="http://vp.soap.base.client.chipkarte.at", IsWrapped=true)]
    public partial class getMessagesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://vp.soap.base.client.chipkarte.at", Order=0)]
        public string dialogId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://vp.soap.base.client.chipkarte.at", Order=1)]
        public bool newOnly;
        
        public getMessagesRequest()
        {
        }
        
        public getMessagesRequest(string dialogId, bool newOnly)
        {
            this.dialogId = dialogId;
            this.newOnly = newOnly;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMessagesResponse", WrapperNamespace="http://vp.soap.base.client.chipkarte.at", IsWrapped=true)]
    public partial class getMessagesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://vp.soap.base.client.chipkarte.at", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getMessagesReturn")]
        public Message[] getMessagesReturn;
        
        public getMessagesResponse()
        {
        }
        
        public getMessagesResponse(Message[] getMessagesReturn)
        {
            this.getMessagesReturn = getMessagesReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getVertraege", WrapperNamespace="http://vp.soap.base.client.chipkarte.at", IsWrapped=true)]
    public partial class getVertraegeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://vp.soap.base.client.chipkarte.at", Order=0)]
        public string dialogId;
        
        public getVertraegeRequest()
        {
        }
        
        public getVertraegeRequest(string dialogId)
        {
            this.dialogId = dialogId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getVertraegeResponse", WrapperNamespace="http://vp.soap.base.client.chipkarte.at", IsWrapped=true)]
    public partial class getVertraegeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://vp.soap.base.client.chipkarte.at", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getVertraegeReturn", IsNullable=true)]
        public VertragsDaten[] getVertraegeReturn;
        
        public getVertraegeResponse()
        {
        }
        
        public getVertraegeResponse(VertragsDaten[] getVertraegeReturn)
        {
            this.getVertraegeReturn = getVertraegeReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSVTs", WrapperNamespace="http://vp.soap.base.client.chipkarte.at", IsWrapped=true)]
    public partial class getSVTsRequest
    {
        
        public getSVTsRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSVTsResponse", WrapperNamespace="http://vp.soap.base.client.chipkarte.at", IsWrapped=true)]
    public partial class getSVTsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://vp.soap.base.client.chipkarte.at", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getSVTsReturn")]
        public SvtProperty[] getSVTsReturn;
        
        public getSVTsResponse()
        {
        }
        
        public getSVTsResponse(SvtProperty[] getSVTsReturn)
        {
            this.getSVTsReturn = getSVTsReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getFachgebiete", WrapperNamespace="http://vp.soap.base.client.chipkarte.at", IsWrapped=true)]
    public partial class getFachgebieteRequest
    {
        
        public getFachgebieteRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getFachgebieteResponse", WrapperNamespace="http://vp.soap.base.client.chipkarte.at", IsWrapped=true)]
    public partial class getFachgebieteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://vp.soap.base.client.chipkarte.at", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getFachgebieteReturn")]
        public BaseProperty[] getFachgebieteReturn;
        
        public getFachgebieteResponse()
        {
        }
        
        public getFachgebieteResponse(BaseProperty[] getFachgebieteReturn)
        {
            this.getFachgebieteReturn = getFachgebieteReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getFachgebieteByOrdId", WrapperNamespace="http://vp.soap.base.client.chipkarte.at", IsWrapped=true)]
    public partial class getFachgebieteByOrdIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://vp.soap.base.client.chipkarte.at", Order=0)]
        public string dialogId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://vp.soap.base.client.chipkarte.at", Order=1)]
        public string ordId;
        
        public getFachgebieteByOrdIdRequest()
        {
        }
        
        public getFachgebieteByOrdIdRequest(string dialogId, string ordId)
        {
            this.dialogId = dialogId;
            this.ordId = ordId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getFachgebieteByOrdIdResponse", WrapperNamespace="http://vp.soap.base.client.chipkarte.at", IsWrapped=true)]
    public partial class getFachgebieteByOrdIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://vp.soap.base.client.chipkarte.at", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getFachgebieteByOrdIdReturn")]
        public BaseProperty[] getFachgebieteByOrdIdReturn;
        
        public getFachgebieteByOrdIdResponse()
        {
        }
        
        public getFachgebieteByOrdIdResponse(BaseProperty[] getFachgebieteByOrdIdReturn)
        {
            this.getFachgebieteByOrdIdReturn = getFachgebieteByOrdIdReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getReaderStatusEvents", WrapperNamespace="http://vp.soap.base.client.chipkarte.at", IsWrapped=true)]
    public partial class getReaderStatusEventsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://vp.soap.base.client.chipkarte.at", Order=0)]
        public string handle;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://vp.soap.base.client.chipkarte.at", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("cardReaderId")]
        public string[] cardReaderId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://vp.soap.base.client.chipkarte.at", Order=2)]
        public int timeOut;
        
        public getReaderStatusEventsRequest()
        {
        }
        
        public getReaderStatusEventsRequest(string handle, string[] cardReaderId, int timeOut)
        {
            this.handle = handle;
            this.cardReaderId = cardReaderId;
            this.timeOut = timeOut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getReaderStatusEventsResponse", WrapperNamespace="http://vp.soap.base.client.chipkarte.at", IsWrapped=true)]
    public partial class getReaderStatusEventsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://vp.soap.base.client.chipkarte.at", Order=0)]
        public AbsCompleteTest.GinaBase7.ReaderStatusResult getReaderStatusEventsReturn;
        
        public getReaderStatusEventsResponse()
        {
        }
        
        public getReaderStatusEventsResponse(AbsCompleteTest.GinaBase7.ReaderStatusResult getReaderStatusEventsReturn)
        {
            this.getReaderStatusEventsReturn = getReaderStatusEventsReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBerechtigungen", WrapperNamespace="http://vp.soap.base.client.chipkarte.at", IsWrapped=true)]
    public partial class getBerechtigungenRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://vp.soap.base.client.chipkarte.at", Order=0)]
        public string dialogId;
        
        public getBerechtigungenRequest()
        {
        }
        
        public getBerechtigungenRequest(string dialogId)
        {
            this.dialogId = dialogId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBerechtigungenResponse", WrapperNamespace="http://vp.soap.base.client.chipkarte.at", IsWrapped=true)]
    public partial class getBerechtigungenResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://vp.soap.base.client.chipkarte.at", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getBerechtigungenReturn")]
        public string[] getBerechtigungenReturn;
        
        public getBerechtigungenResponse()
        {
        }
        
        public getBerechtigungenResponse(string[] getBerechtigungenReturn)
        {
            this.getBerechtigungenReturn = getBerechtigungenReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IBaseServiceVPChannel : AbsCompleteTest.GinaBase7.IBaseServiceVP, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class BaseServiceVPClient : System.ServiceModel.ClientBase<AbsCompleteTest.GinaBase7.IBaseServiceVP>, AbsCompleteTest.GinaBase7.IBaseServiceVP
    {
        
        public BaseServiceVPClient()
        {
        }
        
        public BaseServiceVPClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public BaseServiceVPClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public BaseServiceVPClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public BaseServiceVPClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public string createDialog(string cardReaderId, AbsCompleteTest.GinaBase7.ProduktInfo produktInfo, string extUID)
        {
            return base.Channel.createDialog(cardReaderId, produktInfo, extUID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AbsCompleteTest.GinaBase7.getCardReadersResponse AbsCompleteTest.GinaBase7.IBaseServiceVP.getCardReaders(AbsCompleteTest.GinaBase7.getCardReadersRequest request)
        {
            return base.Channel.getCardReaders(request);
        }
        
        public CardReader[] getCardReaders()
        {
            AbsCompleteTest.GinaBase7.getCardReadersRequest inValue = new AbsCompleteTest.GinaBase7.getCardReadersRequest();
            AbsCompleteTest.GinaBase7.getCardReadersResponse retVal = ((AbsCompleteTest.GinaBase7.IBaseServiceVP)(this)).getCardReaders(inValue);
            return retVal.getCardReadersReturn;
        }
        
        public AbsCompleteTest.GinaBase7.Card getCardData(string cardReaderId)
        {
            return base.Channel.getCardData(cardReaderId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AbsCompleteTest.GinaBase7.getExtendedCardDataResponse AbsCompleteTest.GinaBase7.IBaseServiceVP.getExtendedCardData(AbsCompleteTest.GinaBase7.getExtendedCardDataRequest request)
        {
            return base.Channel.getExtendedCardData(request);
        }
        
        public Property[] getExtendedCardData(string cardReaderId, string CIN)
        {
            AbsCompleteTest.GinaBase7.getExtendedCardDataRequest inValue = new AbsCompleteTest.GinaBase7.getExtendedCardDataRequest();
            inValue.cardReaderId = cardReaderId;
            inValue.CIN = CIN;
            AbsCompleteTest.GinaBase7.getExtendedCardDataResponse retVal = ((AbsCompleteTest.GinaBase7.IBaseServiceVP)(this)).getExtendedCardData(inValue);
            return retVal.getExtendedCardDataReturn;
        }
        
        public void changePin(string cardReaderId, string cin, string oldPin, string newPin)
        {
            base.Channel.changePin(cardReaderId, cin, oldPin, newPin);
        }
        
        public void changePinWithPuk(string cardReaderId, string cin, string puk, string newPin)
        {
            base.Channel.changePinWithPuk(cardReaderId, cin, puk, newPin);
        }
        
        public int doCardTest(string cardReaderId)
        {
            return base.Channel.doCardTest(cardReaderId);
        }
        
        public AbsCompleteTest.GinaBase7.Vertragspartner authenticateDialog(string dialogId, string cin, string pin, int systemType, string cardReaderId)
        {
            return base.Channel.authenticateDialog(dialogId, cin, pin, systemType, cardReaderId);
        }
        
        public void setDialogAddress(string dialogId, string ordinationId)
        {
            base.Channel.setDialogAddress(dialogId, ordinationId);
        }
        
        public void closeDialog(string dialogId)
        {
            base.Channel.closeDialog(dialogId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AbsCompleteTest.GinaBase7.checkStatusResponse AbsCompleteTest.GinaBase7.IBaseServiceVP.checkStatus(AbsCompleteTest.GinaBase7.checkStatusRequest request)
        {
            return base.Channel.checkStatus(request);
        }
        
        public Property[] checkStatus(string dialogId)
        {
            AbsCompleteTest.GinaBase7.checkStatusRequest inValue = new AbsCompleteTest.GinaBase7.checkStatusRequest();
            inValue.dialogId = dialogId;
            AbsCompleteTest.GinaBase7.checkStatusResponse retVal = ((AbsCompleteTest.GinaBase7.IBaseServiceVP)(this)).checkStatus(inValue);
            return retVal.checkStatusReturn;
        }
        
        public void uebersiedelnOrdination(string dialogId, string ordinationId)
        {
            base.Channel.uebersiedelnOrdination(dialogId, ordinationId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AbsCompleteTest.GinaBase7.getMessagesResponse AbsCompleteTest.GinaBase7.IBaseServiceVP.getMessages(AbsCompleteTest.GinaBase7.getMessagesRequest request)
        {
            return base.Channel.getMessages(request);
        }
        
        public Message[] getMessages(string dialogId, bool newOnly)
        {
            AbsCompleteTest.GinaBase7.getMessagesRequest inValue = new AbsCompleteTest.GinaBase7.getMessagesRequest();
            inValue.dialogId = dialogId;
            inValue.newOnly = newOnly;
            AbsCompleteTest.GinaBase7.getMessagesResponse retVal = ((AbsCompleteTest.GinaBase7.IBaseServiceVP)(this)).getMessages(inValue);
            return retVal.getMessagesReturn;
        }
        
        public AbsCompleteTest.GinaBase7.DialogsInfo getFreeDialogs()
        {
            return base.Channel.getFreeDialogs();
        }
        
        public string getGinaSoftwareVersion()
        {
            return base.Channel.getGinaSoftwareVersion();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AbsCompleteTest.GinaBase7.getVertraegeResponse AbsCompleteTest.GinaBase7.IBaseServiceVP.getVertraege(AbsCompleteTest.GinaBase7.getVertraegeRequest request)
        {
            return base.Channel.getVertraege(request);
        }
        
        public VertragsDaten[] getVertraege(string dialogId)
        {
            AbsCompleteTest.GinaBase7.getVertraegeRequest inValue = new AbsCompleteTest.GinaBase7.getVertraegeRequest();
            inValue.dialogId = dialogId;
            AbsCompleteTest.GinaBase7.getVertraegeResponse retVal = ((AbsCompleteTest.GinaBase7.IBaseServiceVP)(this)).getVertraege(inValue);
            return retVal.getVertraegeReturn;
        }
        
        public AbsCompleteTest.GinaBase7.SvPerson getBCardSvPerson(string dialogId, bool forceExecution, string readerId)
        {
            return base.Channel.getBCardSvPerson(dialogId, forceExecution, readerId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AbsCompleteTest.GinaBase7.getSVTsResponse AbsCompleteTest.GinaBase7.IBaseServiceVP.getSVTs(AbsCompleteTest.GinaBase7.getSVTsRequest request)
        {
            return base.Channel.getSVTs(request);
        }
        
        public SvtProperty[] getSVTs()
        {
            AbsCompleteTest.GinaBase7.getSVTsRequest inValue = new AbsCompleteTest.GinaBase7.getSVTsRequest();
            AbsCompleteTest.GinaBase7.getSVTsResponse retVal = ((AbsCompleteTest.GinaBase7.IBaseServiceVP)(this)).getSVTs(inValue);
            return retVal.getSVTsReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AbsCompleteTest.GinaBase7.getFachgebieteResponse AbsCompleteTest.GinaBase7.IBaseServiceVP.getFachgebiete(AbsCompleteTest.GinaBase7.getFachgebieteRequest request)
        {
            return base.Channel.getFachgebiete(request);
        }
        
        public BaseProperty[] getFachgebiete()
        {
            AbsCompleteTest.GinaBase7.getFachgebieteRequest inValue = new AbsCompleteTest.GinaBase7.getFachgebieteRequest();
            AbsCompleteTest.GinaBase7.getFachgebieteResponse retVal = ((AbsCompleteTest.GinaBase7.IBaseServiceVP)(this)).getFachgebiete(inValue);
            return retVal.getFachgebieteReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AbsCompleteTest.GinaBase7.getFachgebieteByOrdIdResponse AbsCompleteTest.GinaBase7.IBaseServiceVP.getFachgebieteByOrdId(AbsCompleteTest.GinaBase7.getFachgebieteByOrdIdRequest request)
        {
            return base.Channel.getFachgebieteByOrdId(request);
        }
        
        public BaseProperty[] getFachgebieteByOrdId(string dialogId, string ordId)
        {
            AbsCompleteTest.GinaBase7.getFachgebieteByOrdIdRequest inValue = new AbsCompleteTest.GinaBase7.getFachgebieteByOrdIdRequest();
            inValue.dialogId = dialogId;
            inValue.ordId = ordId;
            AbsCompleteTest.GinaBase7.getFachgebieteByOrdIdResponse retVal = ((AbsCompleteTest.GinaBase7.IBaseServiceVP)(this)).getFachgebieteByOrdId(inValue);
            return retVal.getFachgebieteByOrdIdReturn;
        }
        
        public AbsCompleteTest.GinaBase7.StatusInformationen getGinaAndServiceavailabilityInformation()
        {
            return base.Channel.getGinaAndServiceavailabilityInformation();
        }
        
        public void setCardReader(string dialogId, string cardReaderId)
        {
            base.Channel.setCardReader(dialogId, cardReaderId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AbsCompleteTest.GinaBase7.getReaderStatusEventsResponse AbsCompleteTest.GinaBase7.IBaseServiceVP.getReaderStatusEvents(AbsCompleteTest.GinaBase7.getReaderStatusEventsRequest request)
        {
            return base.Channel.getReaderStatusEvents(request);
        }
        
        public AbsCompleteTest.GinaBase7.ReaderStatusResult getReaderStatusEvents(string handle, string[] cardReaderId, int timeOut)
        {
            AbsCompleteTest.GinaBase7.getReaderStatusEventsRequest inValue = new AbsCompleteTest.GinaBase7.getReaderStatusEventsRequest();
            inValue.handle = handle;
            inValue.cardReaderId = cardReaderId;
            inValue.timeOut = timeOut;
            AbsCompleteTest.GinaBase7.getReaderStatusEventsResponse retVal = ((AbsCompleteTest.GinaBase7.IBaseServiceVP)(this)).getReaderStatusEvents(inValue);
            return retVal.getReaderStatusEventsReturn;
        }
        
        public void releaseCardReader(string cardReaderId)
        {
            base.Channel.releaseCardReader(cardReaderId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AbsCompleteTest.GinaBase7.getBerechtigungenResponse AbsCompleteTest.GinaBase7.IBaseServiceVP.getBerechtigungen(AbsCompleteTest.GinaBase7.getBerechtigungenRequest request)
        {
            return base.Channel.getBerechtigungen(request);
        }
        
        public string[] getBerechtigungen(string dialogId)
        {
            AbsCompleteTest.GinaBase7.getBerechtigungenRequest inValue = new AbsCompleteTest.GinaBase7.getBerechtigungenRequest();
            inValue.dialogId = dialogId;
            AbsCompleteTest.GinaBase7.getBerechtigungenResponse retVal = ((AbsCompleteTest.GinaBase7.IBaseServiceVP)(this)).getBerechtigungen(inValue);
            return retVal.getBerechtigungenReturn;
        }
    }
}
