//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbsCompleteTest.GinaAbs7
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseException", Namespace="http://exceptions.soap.base.client.chipkarte.at")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AbsCompleteTest.GinaAbs7.ServiceException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AbsCompleteTest.GinaAbs7.DialogException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AbsCompleteTest.GinaAbs7.CardException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AbsCompleteTest.GinaAbs7.InvalidParameterBewilligungsanfrageException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AbsCompleteTest.GinaAbs7.InvalidParameterGetAnfrageStatusException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AbsCompleteTest.GinaAbs7.InvalidParameterRueckantwortException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AbsCompleteTest.GinaAbs7.AccessException))]
    public partial class BaseException : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string codeField;
        
        private int errorCodeField;
        
        private string messageField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceException", Namespace="http://exceptions.soap.base.client.chipkarte.at")]
    public partial class ServiceException : AbsCompleteTest.GinaAbs7.BaseException
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DialogException", Namespace="http://exceptions.soap.base.client.chipkarte.at")]
    public partial class DialogException : AbsCompleteTest.GinaAbs7.BaseException
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardException", Namespace="http://exceptions.soap.base.client.chipkarte.at")]
    public partial class CardException : AbsCompleteTest.GinaAbs7.BaseException
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvalidParameterBewilligungsanfrageException", Namespace="http://exceptions.soap.abs.client.chipkarte.at")]
    public partial class InvalidParameterBewilligungsanfrageException : AbsCompleteTest.GinaAbs7.BaseException
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvalidParameterGetAnfrageStatusException", Namespace="http://exceptions.soap.abs.client.chipkarte.at")]
    public partial class InvalidParameterGetAnfrageStatusException : AbsCompleteTest.GinaAbs7.BaseException
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvalidParameterRueckantwortException", Namespace="http://exceptions.soap.abs.client.chipkarte.at")]
    public partial class InvalidParameterRueckantwortException : AbsCompleteTest.GinaAbs7.BaseException
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccessException", Namespace="http://exceptions.soap.base.client.chipkarte.at")]
    public partial class AccessException : AbsCompleteTest.GinaAbs7.BaseException
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
    [System.Xml.Serialization.XmlRootAttribute(ElementName="fault5", Namespace="http://soap.abs.client.chipkarte.at", IsNullable=false)]
    public partial class AbsException : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Xml.XmlNode[] nodesField;
        
        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("AbsException", "http://exceptions.soap.abs.client.chipkarte.at");
        
        public System.Xml.XmlNode[] Nodes
        {
            get
            {
                return this.nodesField;
            }
            set
            {
                this.nodesField = value;
            }
        }
        
        public void ReadXml(System.Xml.XmlReader reader)
        {
            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
        }
        
        public void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
        }
        
        public System.Xml.Schema.XmlSchema GetSchema()
        {
            return null;
        }
        
        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
        {
            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
            return typeName;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://soap.abs.client.chipkarte.at", ConfigurationName="AbsCompleteTest.GinaAbs7.IAbsService")]
    public interface IAbsService
    {
        
        // CODEGEN: Parameter 'checkStatusReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaAbs7.AccessException), Action="", Name="fault")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaAbs7.DialogException), Action="", Name="fault2")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaAbs7.ServiceException), Action="", Name="fault1")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseProperty))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="checkStatusReturn")]
        AbsCompleteTest.GinaAbs7.checkStatusResponse checkStatus(AbsCompleteTest.GinaAbs7.checkStatusRequest request);
        
        // CODEGEN: Parameter 'getSVTsReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaAbs7.ServiceException), Action="", Name="fault1")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseProperty))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getSVTsReturn")]
        AbsCompleteTest.GinaAbs7.getSVTsResponse getSVTs(AbsCompleteTest.GinaAbs7.getSVTsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaAbs7.AccessException), Action="", Name="fault")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaAbs7.DialogException), Action="", Name="fault2")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaAbs7.InvalidParameterBewilligungsanfrageException), Action="", Name="fault4")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaAbs7.CardException), Action="", Name="fault3")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaAbs7.ServiceException), Action="", Name="fault1")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaAbs7.AbsException), Action="", Name="fault5")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseProperty))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="sendenAnfrageReturn")]
        AbsCompleteTest.GinaAbs7.AnfrageAntwort sendenAnfrage(string dialogId, AbsCompleteTest.GinaAbs7.BewilligungsAnfrage anfrage, string cardReaderId);
        
        // CODEGEN: Parameter 'getStatusBewilligungsAnfragenReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaAbs7.AccessException), Action="", Name="fault")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaAbs7.InvalidParameterGetAnfrageStatusException), Action="", Name="fault6")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaAbs7.DialogException), Action="", Name="fault2")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaAbs7.ServiceException), Action="", Name="fault1")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseProperty))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getStatusBewilligungsAnfragenReturn")]
        AbsCompleteTest.GinaAbs7.getStatusBewilligungsAnfragenResponse getStatusBewilligungsAnfragen(AbsCompleteTest.GinaAbs7.getStatusBewilligungsAnfragenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaAbs7.AccessException), Action="", Name="fault")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaAbs7.DialogException), Action="", Name="fault2")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaAbs7.InvalidParameterRueckantwortException), Action="", Name="fault7")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaAbs7.ServiceException), Action="", Name="fault1")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaAbs7.AbsException), Action="", Name="fault5")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseProperty))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getRueckantwortReturn")]
        AbsCompleteTest.GinaAbs7.Rueckantwort getRueckantwort(string dialogId, string anfrageId);
        
        // CODEGEN: Parameter 'abfragenLangzeitbewilligungReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaAbs7.AccessException), Action="", Name="fault")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaAbs7.DialogException), Action="", Name="fault2")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaAbs7.InvalidParameterBewilligungsanfrageException), Action="", Name="fault4")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaAbs7.CardException), Action="", Name="fault3")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaAbs7.ServiceException), Action="", Name="fault1")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaAbs7.AbsException), Action="", Name="fault5")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseProperty))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="abfragenLangzeitbewilligungReturn")]
        AbsCompleteTest.GinaAbs7.abfragenLangzeitbewilligungResponse abfragenLangzeitbewilligung(AbsCompleteTest.GinaAbs7.abfragenLangzeitbewilligungRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaAbs7.AccessException), Action="", Name="fault")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaAbs7.DialogException), Action="", Name="fault2")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaAbs7.InvalidParameterBewilligungsanfrageException), Action="", Name="fault4")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaAbs7.CardException), Action="", Name="fault3")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaAbs7.ServiceException), Action="", Name="fault1")]
        [System.ServiceModel.FaultContractAttribute(typeof(AbsCompleteTest.GinaAbs7.AbsException), Action="", Name="fault5")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseProperty))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="sendenFolgeverordnungReturn")]
        AbsCompleteTest.GinaAbs7.FolgeverordnungsAusstellungsErgebnis sendenFolgeverordnung(string dialogId, AbsCompleteTest.GinaAbs7.FolgeverordnungsAusstellungsParameter ausstellungsParameter, string cardReaderId);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.base.client.chipkarte.at")]
    public partial class Property
    {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.abs.client.chipkarte.at")]
    public partial class FolgeverordnungsAusstellungsErgebnis
    {
        
        private string sVNRPatientField;
        
        private string sVTCodeField;
        
        private int bewilligteAbgabemengeField;
        
        private string medikamentNameField;
        
        private string nachnamePatientField;
        
        private string pharmanummerField;
        
        private string referenzNrField;
        
        private string vornamePatientField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string SVNRPatient
        {
            get
            {
                return this.sVNRPatientField;
            }
            set
            {
                this.sVNRPatientField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string SVTCode
        {
            get
            {
                return this.sVTCodeField;
            }
            set
            {
                this.sVTCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int bewilligteAbgabemenge
        {
            get
            {
                return this.bewilligteAbgabemengeField;
            }
            set
            {
                this.bewilligteAbgabemengeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string medikamentName
        {
            get
            {
                return this.medikamentNameField;
            }
            set
            {
                this.medikamentNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string nachnamePatient
        {
            get
            {
                return this.nachnamePatientField;
            }
            set
            {
                this.nachnamePatientField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string pharmanummer
        {
            get
            {
                return this.pharmanummerField;
            }
            set
            {
                this.pharmanummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string referenzNr
        {
            get
            {
                return this.referenzNrField;
            }
            set
            {
                this.referenzNrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string vornamePatient
        {
            get
            {
                return this.vornamePatientField;
            }
            set
            {
                this.vornamePatientField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.abs.client.chipkarte.at")]
    public partial class FolgeverordnungsAusstellungsParameter
    {
        
        private string sVNRPatientField;
        
        private string sVTCodeField;
        
        private int beantragteAbgabemengeField;
        
        private string medikamentNameField;
        
        private string pharmanummerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string SVNRPatient
        {
            get
            {
                return this.sVNRPatientField;
            }
            set
            {
                this.sVNRPatientField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string SVTCode
        {
            get
            {
                return this.sVTCodeField;
            }
            set
            {
                this.sVTCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int beantragteAbgabemenge
        {
            get
            {
                return this.beantragteAbgabemengeField;
            }
            set
            {
                this.beantragteAbgabemengeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string medikamentName
        {
            get
            {
                return this.medikamentNameField;
            }
            set
            {
                this.medikamentNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string pharmanummer
        {
            get
            {
                return this.pharmanummerField;
            }
            set
            {
                this.pharmanummerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.abs.client.chipkarte.at")]
    public partial class LangzeitbewilligungsAbfrageErgebnis
    {
        
        private string sVNRPatientField;
        
        private bool abgabeMoeglichField;
        
        private int bewilligteAbgabemengeField;
        
        private string datumGueltigBisField;
        
        private string datumNaechstMoeglicheFolgeverordnungField;
        
        private string dosierungField;
        
        private bool heuteBereitsVerordnetField;
        
        private int heuteBereitsVerordneteMengeField;
        
        private int maximaleAbgabemengeField;
        
        private string medikamentNameField;
        
        private int monatsBedarfField;
        
        private string nachnamePatientField;
        
        private int offeneAbgabemengeField;
        
        private string pharmanummerField;
        
        private string vornamePatientField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string SVNRPatient
        {
            get
            {
                return this.sVNRPatientField;
            }
            set
            {
                this.sVNRPatientField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool abgabeMoeglich
        {
            get
            {
                return this.abgabeMoeglichField;
            }
            set
            {
                this.abgabeMoeglichField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int bewilligteAbgabemenge
        {
            get
            {
                return this.bewilligteAbgabemengeField;
            }
            set
            {
                this.bewilligteAbgabemengeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string datumGueltigBis
        {
            get
            {
                return this.datumGueltigBisField;
            }
            set
            {
                this.datumGueltigBisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string datumNaechstMoeglicheFolgeverordnung
        {
            get
            {
                return this.datumNaechstMoeglicheFolgeverordnungField;
            }
            set
            {
                this.datumNaechstMoeglicheFolgeverordnungField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string dosierung
        {
            get
            {
                return this.dosierungField;
            }
            set
            {
                this.dosierungField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool heuteBereitsVerordnet
        {
            get
            {
                return this.heuteBereitsVerordnetField;
            }
            set
            {
                this.heuteBereitsVerordnetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int heuteBereitsVerordneteMenge
        {
            get
            {
                return this.heuteBereitsVerordneteMengeField;
            }
            set
            {
                this.heuteBereitsVerordneteMengeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int maximaleAbgabemenge
        {
            get
            {
                return this.maximaleAbgabemengeField;
            }
            set
            {
                this.maximaleAbgabemengeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string medikamentName
        {
            get
            {
                return this.medikamentNameField;
            }
            set
            {
                this.medikamentNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int monatsBedarf
        {
            get
            {
                return this.monatsBedarfField;
            }
            set
            {
                this.monatsBedarfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string nachnamePatient
        {
            get
            {
                return this.nachnamePatientField;
            }
            set
            {
                this.nachnamePatientField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int offeneAbgabemenge
        {
            get
            {
                return this.offeneAbgabemengeField;
            }
            set
            {
                this.offeneAbgabemengeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public string pharmanummer
        {
            get
            {
                return this.pharmanummerField;
            }
            set
            {
                this.pharmanummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public string vornamePatient
        {
            get
            {
                return this.vornamePatientField;
            }
            set
            {
                this.vornamePatientField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.abs.client.chipkarte.at")]
    public partial class LangzeitVerordnung
    {
        
        private int beantragteMonateField;
        
        private int bewilligteMonateField;
        
        private int bewilligtePackungenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int beantragteMonate
        {
            get
            {
                return this.beantragteMonateField;
            }
            set
            {
                this.beantragteMonateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int bewilligteMonate
        {
            get
            {
                return this.bewilligteMonateField;
            }
            set
            {
                this.bewilligteMonateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int bewilligtePackungen
        {
            get
            {
                return this.bewilligtePackungenField;
            }
            set
            {
                this.bewilligtePackungenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.abs.client.chipkarte.at")]
    public partial class AnfrageEntscheid
    {
        
        private int beantragtePackungsanzahlField;
        
        private Medikament beantragtesMedikamentField;
        
        private int bewilligtePackungsanzahlField;
        
        private Medikament bewilligtesMedikamentField;
        
        private string infoTextField;
        
        private LangzeitVerordnung langzeitVerordnungField;
        
        private string magistraleZubereitungField;
        
        private string verordnungsEntscheidungField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int beantragtePackungsanzahl
        {
            get
            {
                return this.beantragtePackungsanzahlField;
            }
            set
            {
                this.beantragtePackungsanzahlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public Medikament beantragtesMedikament
        {
            get
            {
                return this.beantragtesMedikamentField;
            }
            set
            {
                this.beantragtesMedikamentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int bewilligtePackungsanzahl
        {
            get
            {
                return this.bewilligtePackungsanzahlField;
            }
            set
            {
                this.bewilligtePackungsanzahlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public Medikament bewilligtesMedikament
        {
            get
            {
                return this.bewilligtesMedikamentField;
            }
            set
            {
                this.bewilligtesMedikamentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string infoText
        {
            get
            {
                return this.infoTextField;
            }
            set
            {
                this.infoTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public LangzeitVerordnung langzeitVerordnung
        {
            get
            {
                return this.langzeitVerordnungField;
            }
            set
            {
                this.langzeitVerordnungField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string magistraleZubereitung
        {
            get
            {
                return this.magistraleZubereitungField;
            }
            set
            {
                this.magistraleZubereitungField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string verordnungsEntscheidung
        {
            get
            {
                return this.verordnungsEntscheidungField;
            }
            set
            {
                this.verordnungsEntscheidungField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.abs.client.chipkarte.at")]
    public partial class Medikament
    {
        
        private string nameField;
        
        private string pharmanummerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string pharmanummer
        {
            get
            {
                return this.pharmanummerField;
            }
            set
            {
                this.pharmanummerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.abs.client.chipkarte.at")]
    public partial class Rueckantwort
    {
        
        private string eKVKPatientField;
        
        private string sVNRPatientField;
        
        private string abfrageZeitpunktField;
        
        private AnfrageEntscheid[] anfrageEntscheideField;
        
        private string anfrageIdField;
        
        private string antragstypField;
        
        private string beantwortungsZeitpunktField;
        
        private BewilligungsAnfrage bewilligungsAnfrageField;
        
        private string einlangeZeitpunktField;
        
        private string infoTextField;
        
        private string nachnamePatientField;
        
        private string referenzIdField;
        
        private string vornamePatientField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string EKVKPatient
        {
            get
            {
                return this.eKVKPatientField;
            }
            set
            {
                this.eKVKPatientField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string SVNRPatient
        {
            get
            {
                return this.sVNRPatientField;
            }
            set
            {
                this.sVNRPatientField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string abfrageZeitpunkt
        {
            get
            {
                return this.abfrageZeitpunktField;
            }
            set
            {
                this.abfrageZeitpunktField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("anfrageEntscheide", IsNullable=true, Order=3)]
        public AnfrageEntscheid[] anfrageEntscheide
        {
            get
            {
                return this.anfrageEntscheideField;
            }
            set
            {
                this.anfrageEntscheideField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string anfrageId
        {
            get
            {
                return this.anfrageIdField;
            }
            set
            {
                this.anfrageIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string antragstyp
        {
            get
            {
                return this.antragstypField;
            }
            set
            {
                this.antragstypField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string beantwortungsZeitpunkt
        {
            get
            {
                return this.beantwortungsZeitpunktField;
            }
            set
            {
                this.beantwortungsZeitpunktField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public BewilligungsAnfrage bewilligungsAnfrage
        {
            get
            {
                return this.bewilligungsAnfrageField;
            }
            set
            {
                this.bewilligungsAnfrageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string einlangeZeitpunkt
        {
            get
            {
                return this.einlangeZeitpunktField;
            }
            set
            {
                this.einlangeZeitpunktField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string infoText
        {
            get
            {
                return this.infoTextField;
            }
            set
            {
                this.infoTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string nachnamePatient
        {
            get
            {
                return this.nachnamePatientField;
            }
            set
            {
                this.nachnamePatientField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string referenzId
        {
            get
            {
                return this.referenzIdField;
            }
            set
            {
                this.referenzIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public string vornamePatient
        {
            get
            {
                return this.vornamePatientField;
            }
            set
            {
                this.vornamePatientField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.abs.client.chipkarte.at")]
    public partial class BewilligungsAnfrage
    {
        
        private string antragstypField;
        
        private PatientenDaten patientenDatenField;
        
        private string verordnerinformationField;
        
        private Verordnung[] verordnungenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string antragstyp
        {
            get
            {
                return this.antragstypField;
            }
            set
            {
                this.antragstypField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public PatientenDaten patientenDaten
        {
            get
            {
                return this.patientenDatenField;
            }
            set
            {
                this.patientenDatenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string verordnerinformation
        {
            get
            {
                return this.verordnerinformationField;
            }
            set
            {
                this.verordnerinformationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("verordnungen", IsNullable=true, Order=3)]
        public Verordnung[] verordnungen
        {
            get
            {
                return this.verordnungenField;
            }
            set
            {
                this.verordnungenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.abs.client.chipkarte.at")]
    public partial class PatientenDaten
    {
        
        private string eKVKNummerField;
        
        private string sVNummerField;
        
        private string sVTCodeField;
        
        private string geschlechtField;
        
        private string nachnameField;
        
        private string vornameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string EKVKNummer
        {
            get
            {
                return this.eKVKNummerField;
            }
            set
            {
                this.eKVKNummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string SVNummer
        {
            get
            {
                return this.sVNummerField;
            }
            set
            {
                this.sVNummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string SVTCode
        {
            get
            {
                return this.sVTCodeField;
            }
            set
            {
                this.sVTCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string geschlecht
        {
            get
            {
                return this.geschlechtField;
            }
            set
            {
                this.geschlechtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string nachname
        {
            get
            {
                return this.nachnameField;
            }
            set
            {
                this.nachnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string vorname
        {
            get
            {
                return this.vornameField;
            }
            set
            {
                this.vornameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.abs.client.chipkarte.at")]
    public partial class Verordnung
    {
        
        private string begruendungField;
        
        private string diagnoseField;
        
        private string dosierungField;
        
        private string langzeitverordnungField;
        
        private string magistraleZubereitungField;
        
        private Medikament medikamentField;
        
        private int packungsanzahlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string begruendung
        {
            get
            {
                return this.begruendungField;
            }
            set
            {
                this.begruendungField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string diagnose
        {
            get
            {
                return this.diagnoseField;
            }
            set
            {
                this.diagnoseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string dosierung
        {
            get
            {
                return this.dosierungField;
            }
            set
            {
                this.dosierungField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string langzeitverordnung
        {
            get
            {
                return this.langzeitverordnungField;
            }
            set
            {
                this.langzeitverordnungField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string magistraleZubereitung
        {
            get
            {
                return this.magistraleZubereitungField;
            }
            set
            {
                this.magistraleZubereitungField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public Medikament medikament
        {
            get
            {
                return this.medikamentField;
            }
            set
            {
                this.medikamentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int packungsanzahl
        {
            get
            {
                return this.packungsanzahlField;
            }
            set
            {
                this.packungsanzahlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.abs.client.chipkarte.at")]
    public partial class StatusBewilligungsAnfrage
    {
        
        private string eKVKNummerField;
        
        private string sVNRPatientField;
        
        private string abfrageZeitpunktField;
        
        private string anfrageIdField;
        
        private string beantwortungsZeitpunktField;
        
        private string einlangeZeitpunktField;
        
        private string nachnamePatientField;
        
        private string vornamePatientField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string EKVKNummer
        {
            get
            {
                return this.eKVKNummerField;
            }
            set
            {
                this.eKVKNummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string SVNRPatient
        {
            get
            {
                return this.sVNRPatientField;
            }
            set
            {
                this.sVNRPatientField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string abfrageZeitpunkt
        {
            get
            {
                return this.abfrageZeitpunktField;
            }
            set
            {
                this.abfrageZeitpunktField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string anfrageId
        {
            get
            {
                return this.anfrageIdField;
            }
            set
            {
                this.anfrageIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string beantwortungsZeitpunkt
        {
            get
            {
                return this.beantwortungsZeitpunktField;
            }
            set
            {
                this.beantwortungsZeitpunktField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string einlangeZeitpunkt
        {
            get
            {
                return this.einlangeZeitpunktField;
            }
            set
            {
                this.einlangeZeitpunktField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string nachnamePatient
        {
            get
            {
                return this.nachnamePatientField;
            }
            set
            {
                this.nachnamePatientField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string vornamePatient
        {
            get
            {
                return this.vornamePatientField;
            }
            set
            {
                this.vornamePatientField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.abs.client.chipkarte.at")]
    public partial class FilterKriterien
    {
        
        private string anfrageStatusField;
        
        private string datumBisField;
        
        private string datumVonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string anfrageStatus
        {
            get
            {
                return this.anfrageStatusField;
            }
            set
            {
                this.anfrageStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string datumBis
        {
            get
            {
                return this.datumBisField;
            }
            set
            {
                this.datumBisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string datumVon
        {
            get
            {
                return this.datumVonField;
            }
            set
            {
                this.datumVonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.abs.client.chipkarte.at")]
    public partial class AnfrageAntwort
    {
        
        private bool bearbeitungNaechsterWerktagField;
        
        private string idField;
        
        private PatientenDaten patientenDatenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool bearbeitungNaechsterWerktag
        {
            get
            {
                return this.bearbeitungNaechsterWerktagField;
            }
            set
            {
                this.bearbeitungNaechsterWerktagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public PatientenDaten patientenDaten
        {
            get
            {
                return this.patientenDatenField;
            }
            set
            {
                this.patientenDatenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SvtProperty))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.base.client.chipkarte.at")]
    public partial class BaseProperty
    {
        
        private string codeField;
        
        private bool nurAnzeigeField;
        
        private string textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool nurAnzeige
        {
            get
            {
                return this.nurAnzeigeField;
            }
            set
            {
                this.nurAnzeigeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.base.client.chipkarte.at")]
    public partial class SvtProperty : BaseProperty
    {
        
        private bool aSVGField;
        
        private string eKVKCodeField;
        
        private string eKVKNameField;
        
        private string kurzbezeichnungField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool ASVG
        {
            get
            {
                return this.aSVGField;
            }
            set
            {
                this.aSVGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string EKVKCode
        {
            get
            {
                return this.eKVKCodeField;
            }
            set
            {
                this.eKVKCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string EKVKName
        {
            get
            {
                return this.eKVKNameField;
            }
            set
            {
                this.eKVKNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string kurzbezeichnung
        {
            get
            {
                return this.kurzbezeichnungField;
            }
            set
            {
                this.kurzbezeichnungField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkStatus", WrapperNamespace="http://soap.abs.client.chipkarte.at", IsWrapped=true)]
    public partial class checkStatusRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.abs.client.chipkarte.at", Order=0)]
        public string dialogId;
        
        public checkStatusRequest()
        {
        }
        
        public checkStatusRequest(string dialogId)
        {
            this.dialogId = dialogId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkStatusResponse", WrapperNamespace="http://soap.abs.client.chipkarte.at", IsWrapped=true)]
    public partial class checkStatusResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.abs.client.chipkarte.at", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("checkStatusReturn")]
        public Property[] checkStatusReturn;
        
        public checkStatusResponse()
        {
        }
        
        public checkStatusResponse(Property[] checkStatusReturn)
        {
            this.checkStatusReturn = checkStatusReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSVTs", WrapperNamespace="http://soap.abs.client.chipkarte.at", IsWrapped=true)]
    public partial class getSVTsRequest
    {
        
        public getSVTsRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSVTsResponse", WrapperNamespace="http://soap.abs.client.chipkarte.at", IsWrapped=true)]
    public partial class getSVTsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.abs.client.chipkarte.at", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getSVTsReturn")]
        public SvtProperty[] getSVTsReturn;
        
        public getSVTsResponse()
        {
        }
        
        public getSVTsResponse(SvtProperty[] getSVTsReturn)
        {
            this.getSVTsReturn = getSVTsReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStatusBewilligungsAnfragen", WrapperNamespace="http://soap.abs.client.chipkarte.at", IsWrapped=true)]
    public partial class getStatusBewilligungsAnfragenRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.abs.client.chipkarte.at", Order=0)]
        public string dialogId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.abs.client.chipkarte.at", Order=1)]
        public AbsCompleteTest.GinaAbs7.FilterKriterien filterkriterien;
        
        public getStatusBewilligungsAnfragenRequest()
        {
        }
        
        public getStatusBewilligungsAnfragenRequest(string dialogId, AbsCompleteTest.GinaAbs7.FilterKriterien filterkriterien)
        {
            this.dialogId = dialogId;
            this.filterkriterien = filterkriterien;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStatusBewilligungsAnfragenResponse", WrapperNamespace="http://soap.abs.client.chipkarte.at", IsWrapped=true)]
    public partial class getStatusBewilligungsAnfragenResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.abs.client.chipkarte.at", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getStatusBewilligungsAnfragenReturn")]
        public StatusBewilligungsAnfrage[] getStatusBewilligungsAnfragenReturn;
        
        public getStatusBewilligungsAnfragenResponse()
        {
        }
        
        public getStatusBewilligungsAnfragenResponse(StatusBewilligungsAnfrage[] getStatusBewilligungsAnfragenReturn)
        {
            this.getStatusBewilligungsAnfragenReturn = getStatusBewilligungsAnfragenReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="abfragenLangzeitbewilligung", WrapperNamespace="http://soap.abs.client.chipkarte.at", IsWrapped=true)]
    public partial class abfragenLangzeitbewilligungRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.abs.client.chipkarte.at", Order=0)]
        public string dialogId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.abs.client.chipkarte.at", Order=1)]
        public string sVNRPatient;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.abs.client.chipkarte.at", Order=2)]
        public string cardReaderId;
        
        public abfragenLangzeitbewilligungRequest()
        {
        }
        
        public abfragenLangzeitbewilligungRequest(string dialogId, string sVNRPatient, string cardReaderId)
        {
            this.dialogId = dialogId;
            this.sVNRPatient = sVNRPatient;
            this.cardReaderId = cardReaderId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="abfragenLangzeitbewilligungResponse", WrapperNamespace="http://soap.abs.client.chipkarte.at", IsWrapped=true)]
    public partial class abfragenLangzeitbewilligungResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.abs.client.chipkarte.at", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("abfragenLangzeitbewilligungReturn")]
        public LangzeitbewilligungsAbfrageErgebnis[] abfragenLangzeitbewilligungReturn;
        
        public abfragenLangzeitbewilligungResponse()
        {
        }
        
        public abfragenLangzeitbewilligungResponse(LangzeitbewilligungsAbfrageErgebnis[] abfragenLangzeitbewilligungReturn)
        {
            this.abfragenLangzeitbewilligungReturn = abfragenLangzeitbewilligungReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IAbsServiceChannel : AbsCompleteTest.GinaAbs7.IAbsService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class AbsServiceClient : System.ServiceModel.ClientBase<AbsCompleteTest.GinaAbs7.IAbsService>, AbsCompleteTest.GinaAbs7.IAbsService
    {
        
        public AbsServiceClient()
        {
        }
        
        public AbsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public AbsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public AbsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public AbsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AbsCompleteTest.GinaAbs7.checkStatusResponse AbsCompleteTest.GinaAbs7.IAbsService.checkStatus(AbsCompleteTest.GinaAbs7.checkStatusRequest request)
        {
            return base.Channel.checkStatus(request);
        }
        
        public Property[] checkStatus(string dialogId)
        {
            AbsCompleteTest.GinaAbs7.checkStatusRequest inValue = new AbsCompleteTest.GinaAbs7.checkStatusRequest();
            inValue.dialogId = dialogId;
            AbsCompleteTest.GinaAbs7.checkStatusResponse retVal = ((AbsCompleteTest.GinaAbs7.IAbsService)(this)).checkStatus(inValue);
            return retVal.checkStatusReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AbsCompleteTest.GinaAbs7.getSVTsResponse AbsCompleteTest.GinaAbs7.IAbsService.getSVTs(AbsCompleteTest.GinaAbs7.getSVTsRequest request)
        {
            return base.Channel.getSVTs(request);
        }
        
        public SvtProperty[] getSVTs()
        {
            AbsCompleteTest.GinaAbs7.getSVTsRequest inValue = new AbsCompleteTest.GinaAbs7.getSVTsRequest();
            AbsCompleteTest.GinaAbs7.getSVTsResponse retVal = ((AbsCompleteTest.GinaAbs7.IAbsService)(this)).getSVTs(inValue);
            return retVal.getSVTsReturn;
        }
        
        public AbsCompleteTest.GinaAbs7.AnfrageAntwort sendenAnfrage(string dialogId, AbsCompleteTest.GinaAbs7.BewilligungsAnfrage anfrage, string cardReaderId)
        {
            return base.Channel.sendenAnfrage(dialogId, anfrage, cardReaderId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AbsCompleteTest.GinaAbs7.getStatusBewilligungsAnfragenResponse AbsCompleteTest.GinaAbs7.IAbsService.getStatusBewilligungsAnfragen(AbsCompleteTest.GinaAbs7.getStatusBewilligungsAnfragenRequest request)
        {
            return base.Channel.getStatusBewilligungsAnfragen(request);
        }
        
        public StatusBewilligungsAnfrage[] getStatusBewilligungsAnfragen(string dialogId, AbsCompleteTest.GinaAbs7.FilterKriterien filterkriterien)
        {
            AbsCompleteTest.GinaAbs7.getStatusBewilligungsAnfragenRequest inValue = new AbsCompleteTest.GinaAbs7.getStatusBewilligungsAnfragenRequest();
            inValue.dialogId = dialogId;
            inValue.filterkriterien = filterkriterien;
            AbsCompleteTest.GinaAbs7.getStatusBewilligungsAnfragenResponse retVal = ((AbsCompleteTest.GinaAbs7.IAbsService)(this)).getStatusBewilligungsAnfragen(inValue);
            return retVal.getStatusBewilligungsAnfragenReturn;
        }
        
        public AbsCompleteTest.GinaAbs7.Rueckantwort getRueckantwort(string dialogId, string anfrageId)
        {
            return base.Channel.getRueckantwort(dialogId, anfrageId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AbsCompleteTest.GinaAbs7.abfragenLangzeitbewilligungResponse AbsCompleteTest.GinaAbs7.IAbsService.abfragenLangzeitbewilligung(AbsCompleteTest.GinaAbs7.abfragenLangzeitbewilligungRequest request)
        {
            return base.Channel.abfragenLangzeitbewilligung(request);
        }
        
        public LangzeitbewilligungsAbfrageErgebnis[] abfragenLangzeitbewilligung(string dialogId, string sVNRPatient, string cardReaderId)
        {
            AbsCompleteTest.GinaAbs7.abfragenLangzeitbewilligungRequest inValue = new AbsCompleteTest.GinaAbs7.abfragenLangzeitbewilligungRequest();
            inValue.dialogId = dialogId;
            inValue.sVNRPatient = sVNRPatient;
            inValue.cardReaderId = cardReaderId;
            AbsCompleteTest.GinaAbs7.abfragenLangzeitbewilligungResponse retVal = ((AbsCompleteTest.GinaAbs7.IAbsService)(this)).abfragenLangzeitbewilligung(inValue);
            return retVal.abfragenLangzeitbewilligungReturn;
        }
        
        public AbsCompleteTest.GinaAbs7.FolgeverordnungsAusstellungsErgebnis sendenFolgeverordnung(string dialogId, AbsCompleteTest.GinaAbs7.FolgeverordnungsAusstellungsParameter ausstellungsParameter, string cardReaderId)
        {
            return base.Channel.sendenFolgeverordnung(dialogId, ausstellungsParameter, cardReaderId);
        }
    }
}
